frontend/components/Main/MainHeader.tsx
`totalOlasBalance` & `totalEthBalance` can be `undefined`
falling back to 0 so the conditions render the disabled button during this period.
=> fix: start agent button conditions

frontend/components/Main/MainHeader.tsx, frontend/service/Services.ts
re: tray icons changes to "running" and notification shows even if the createService fails
the problem was that in case of an unsuccessful response, it didn't fall into the "catch" block
=> Handle createService failing correctly

frontend/components/Main/MainNeedsFunds.tsx, frontend/components/Setup/Create/SetupEoaFunding.tsx, frontend/components/Setup/Setup.tsx, frontend/components/Setup/SetupWelcome.tsx, frontend/enums/SetupScreen.ts
https://github.com/valory-xyz/olas-operate-app/assets/22725775/dae336b5-3a28-42f4-ac63-1cc05777c3bc
=> Navigate to send funds if eoa balance is empty

frontend/components/Main/MainHeader.tsx, frontend/components/Setup/SetupWelcome.tsx
- start agent button was disabled in some states where it shouldn't be
=> fix start agent balance thresholds

frontend/components/Main/MainHeader.tsx, frontend/components/Main/MainNeedsFunds.tsx
safe's staked funds were not considered in OLAS balance, resulting in visible "needs funds" alert
- added staked OLAS funds in condition
- also, adjusted some Start Agent conditions to implement similar logic (edge cases where users could send OLAS to other wallets considered in totalOlasBalance)
=> Fix "needs funds" Alert visibility

frontend/components/Settings/DebugInfoCard.tsx, frontend/components/Settings/Settings.tsx, frontend/styles/globals.scss
1. removed displaying backup wallet, bc we can't display it's balance anyway and we have it on previous screen
2. in Figma there's a box shadow under the header when the content is scrolled - I wasn't able to add it with css only, don't think we need a solution with scroll listeners, having that we request data by intervals... but lmkyt if someone feels it's important
loading state (unlikely to be seen though, we have all data loaded at this point):
flow:
https://github.com/valory-xyz/olas-operate-app/assets/22725775/d2f206a4-a654-4c67-b811-e59e37dbf133
=> Add debug modal

frontend/context/ElectronApiProvider.tsx
- return type expected for initial state object, object was empty; build failed during release
=> feat: update saveLogs function initial value to expected type

electron/main.js, frontend/components/Main/KeepAgentRunning.tsx, frontend/components/Main/MainHeader.tsx, frontend/components/Main/MainOlasBalance.tsx, frontend/components/Main/MainRewards.tsx, frontend/constants/color.ts, frontend/context/ElectronApiProvider.tsx, frontend/hooks/useReward.ts, frontend/styles/globals.scss
what's changed:
1) "Staking Rewards Today" changed to "Staking Rewards This Work Period," with a tooltip providing further explanation.
2) The staked amount block removed.
3) A breakdown of the balance added.
4) The "Start agent" button now has the "& stake" postfix, If it is the agent's first run. After first run the modal is shown and notification text is updated
| Full view      | Rewards tooltip | Balance breakdown b/ staking | After staking | Modal |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| ![image](https://github.com/valory-xyz/olas-operate-app/assets/22725775/56a5b116-b0ff-4402-ba47-ff3b925cbea1)      | <img width="468" alt="Screenshot 2024-06-03 at 10 05 58" src="https://github.com/valory-xyz/olas-operate-app/assets/22725775/a2301df6-e498-4e3d-9a84- …
=> Add rewards today tooltip

frontend/components/Setup/Create/SetupBackupSigner.tsx
Users were previously able to skip backup wallet definition, but have temporarlily removed to protect users during alpha.
=> Comment out Skip button during Wallet Backup screen

operate/cli.py, operate/services/manage.py
This PR fixes key management as follows.
Previously, keys for a service were freshly created, but only stored once the service mint-activation-registration process was successful on-chain.
If that proces broke somewhere, the middleware would create new fresh keys for the service agents, which would lead to duplicate keys on the .operate/keys folder.
The current approach creates fresh keys when the Service object is created (not loaded from an existing file). Therefore, keys are always stored in the config.json file upon service creation. This will ensure that no duplicate keys are created if the on-chain process fails.
Note: this uncovered an issue with the front-end #227
=> Fix duplicte keys creation

frontend/constants/serviceTemplates.ts, templates/trader.yaml
Fix image hash. The image NFT hash had been inadvertently changed both in `trader.yaml` and `serviceTemplate.ts`. This has no major effect other than displaying a wrong image for the agent.
=> Fix image hash

frontend/components/Main/MainHeader/FirstRunModal.tsx, frontend/components/Main/MainHeader/index.tsx, frontend/components/Main/MainNeedsFunds.tsx, frontend/components/Main/MainRewards.tsx, frontend/context/RewardProvider.tsx, frontend/hooks/useReward.ts, frontend/utils/service.ts
There are two issues with notifications:
1) On the first run, a user should stake 20 OLAS. When the agent runs for the first time, we show a modal and a notification. The problem is that the notification shows "undefined" instead of "20" because we get the value from the existing service, which is actually not yet created when we call showNotification.
I changed the logic to get the `minimumStakedAmountRequired` from the template instead of from the service and removed it from the `useReward` since it's not used anywhere else. I also updated the NeedsFunds modal so it has the same source of truth.
The error:
After the fix:
2)The "first staking rewards earned" notification is shown for me multiple times in a row until the modal is closed. It happens due to the fact that useEffect has …
=> fix: notifications fixes

electron/constants/index.js, electron/install.js, electron/main.js, package.json, pyproject.toml
Fix missing tendermint installation.
If not present on the PATH, tendermint will be downloaded and sudo-installed on `/usr/local/bin/tendermint`. This will promt the sudo password to the user.
=> Fix missing tendermint installation

download_binaries.sh, package.json
Trello Ticket : https://trello.com/c/8sADgND3/1992-add-binary-download-step-to-yarn-build-sarthak
Description: add download binaries script.
=> add download binaries script

build_pearl.sh, package.json
Trello Ticket: https://trello.com/c/tumGdJxq/2020-script-to-build-the-operate-cli-into-pyinstaller-binary-enables-local-testing-in-production-mode
=> Script for building middleware binary locally 

frontend/components/Main/MainGasBalance.tsx, frontend/components/Main/MainHeader/AgentButton/index.tsx, frontend/components/Main/MainHeader/index.tsx, frontend/components/Main/MainOlasBalance.tsx, frontend/constants/thresholds.ts, frontend/context/BalanceProvider.tsx
The change is based on this logic: https://github.com/valory-xyz/olas-operate-app/issues/273#issuecomment-2285921077
How it works:
1) when master safe balance is 1 XDAI, but agent safe has funds, e.g. 5 XDAI - we don't show the alert, notification, red dot, etc.
2) when master safe balance is 1XDAI, and agent safe balance is 0.25 XDA, we show all the low gas info
=> chore: update low gas alert logic

electron/install.js, frontend/pages/_app.tsx, package.json, pyproject.toml
Rewards provider required StakingProgram, and was not in the correct order.
Providers have been grouped and improved in: https://github.com/valory-xyz/olas-operate-app/pull/288 to reduce complexity and chances of this happening in future.
---
This is the PR for the successfully tested, draft released, contract migration version of Pearl, [rc116](https://github.com/valory-xyz/olas-operate-app/releases/tag/untagged-83bd1e435d294603b869).
Will need to merge to staging, and then to main, bumping for full release.
=> Fix for Broken Rewards

frontend/components/ManageStakingPage/StakingContractSection/index.tsx, frontend/components/ManageStakingPage/index.tsx
Stopped iterating over staking contracts, instead used separate components. Too error prone if the ordering changes.
Only showing Migrate button on Pearl Beta section, Alpha should not be migrated to. Users were unable to migrate regardless, but removing redundancy here.
=> refactor: removed migration button from Pearl Alpha section

frontend/components/ManageStakingPage/StakingContractSection/index.tsx
Funding section and top-up alert no longer shows if the user is ineligible to migrate due to not being staked long enough.
=> fix: hide funding until completed staking period

frontend/components/MainPage/header/AgentButton.tsx
Removed as per @oaksprout's request.
=> fix: remove hardcoded OLAS requirement from "now running" notification

.github/workflows/release_win.yml, frontend/components/ManageStakingPage/StakingContractSection/index.tsx
includes @jmoreira-valory's [fix: disable hash update](https://github.com/valory-xyz/olas-operate-app/commit/7d1c6ef86d2913b5651fd15fc7da5a9fe308fa43)
added [fix: migration countdown, and minimum duration fix from staging](https://github.com/valory-xyz/olas-operate-app/commit/5d2720db93adcb9158924ea7f838134c4807f27e)
copied fix for hiding funding options (merged earlier to staging) when user is not able to migrate due to staking duration
=> fix: disabled on-chain hash update, added countdown until user can migrate

frontend/components/SettingsPage/DebugInfoSection.tsx
Commented too much code when removing the broken pandora link in #328.
=> fix: redisplay missing agent safe info in debug window

electron/main.js
Was unable to export logs smoothly as `:` used to seperate ISO time string was blocked on Windows
=> fix: make log export Windows friendly (`:` not supported in filename)

frontend/components/SetupPage/Create/SetupBackupSigner.tsx
@oaksprout mentioned he experienced errors when backup wallet address was not checksummed
fix **ensures the address is checksummed in the background**
- allows for non-checksummed input (as to not frustrate users)
- will send the checksummed address to middleware when creating a safe (to add as signer)
tried using validation `rules` on the Antd input, but `transform` and `validator` functions don't update input value. hence the validation on submit.
should resolve #331, [Trello ticket](https://trello.com/c/Cp0Q36i9/2141-backup-wallet-is-not-added)
(made [a small fix](https://github.com/valory-xyz/olas-operate-app/pull/351/commits/32d137934cee0b91e90f76a2fbdf3726a9886e61) mid way through, works as expected now)
https://github.com/user-attachments/assets/0ad0af9d-00c2-4013-8f82-29a0219de381
=> fix: ensure backup address is checksummed before submitting to backend

electron/main.js
Added logging around single instance locking
Added event handler to bring active Pearl window into focus if another instance is started
https://github.com/user-attachments/assets/5f9f320f-d909-404b-a4c2-783996a71ff3
=> fix: display primary instance when attempting to start another

frontend/components/MainPage/header/AgentButton.tsx, frontend/context/StakingContractInfoProvider.tsx, frontend/hooks/useStakingContractInfo.ts
- paused staking contract info polling while deploying
- added 5s timeout after deployment success response as a workaround
**not** a good approach, would prefer to receive success responses from middleware once agent is confirmed deployed, staked, and running ..
however, in the interest of having this patched for tomorrow, have raised this PR
**balance transition** 
experienced as service is progressing through registry service states
only seen when deploying for the first time
https://github.com/user-attachments/assets/5ebcdc03-768d-48eb-96c0-b15ea641cff4
=> fix: cannot start agent glitch (workaround )

.gitleaks.toml
allowlisting EVM public keys, stops CI failures whenever contracts are added/updated
=> fix: allowlist evm public keys in gitleaks CI

electron/install.js, frontend/components/SetupPage/Create/SetupCreateSafe.tsx, frontend/components/SetupPage/Create/SetupSeedPhrase.tsx, frontend/components/styled/CardFlex.tsx, frontend/constants/headers.ts, frontend/context/MasterSafeProvider.tsx, frontend/context/ServicesProvider.tsx, frontend/context/WalletProvider.tsx, frontend/service/Account.ts, frontend/service/Services.ts, frontend/service/Wallet.ts, package.json, pyproject.toml
- update API services to parse error statuses and throw
- add utf-8 charset, unlikely to be required, but may support decoding issues on middleware 
- add create safe retries
- updates "creating safe" text at different steps
- check backup signer exists before continuing to main (stops missing backup wallet alert appearing)
- added error message notifications during creation (i.e. if retrying)
no real UI changes, will ask @iasonrovis to test rc162
=> fix: fetch response parsing, create safe retry

.github/workflows/backend.yml, .github/workflows/frontend.yml, .github/workflows/release.yml, .github/workflows/release_win.yml, build-win-tenderly.js, build-win.js, build.js, build.tester.js, package.json, pyproject.toml, yarn.lock
- fixed python missing ssl and virtualenv modules
- replaced macos-large-14 github runner, consistently fails on python ssl
- avoiding yarn timeout issues by reducing network concurrency, extending retry delay
- updated electron as electron 30 is deprecated
- removed error catching on release process for CI failure when error occurs
- updated APPLETEAMID env var; removed from build.js, renamed in env to APPLE_TEAM_ID (required for updated electron packages)
=> fix: multiple workflow issues, electron updated to latest as 30 is deprecated

frontend/client/types.ts, frontend/constants/serviceTemplates.ts, operate/operate_types.py, operate/services/health_checker.py, operate/services/manage.py, operate/services/service.py, operate/wallet/master.py
=> Compute env vars

operate/services/manage.py, operate/services/service.py
=> Fix usage of chain_id

frontend/components/YourWalletPage/index.tsx
Update page that displays your wallet balances to use new hooks .etc
=> Fix "Your Wallet" page

frontend/components/ManageStakingPage/index.tsx, frontend/hooks/useLogs.ts
Few fixes to show login screen..
ssheeeeeeshshh
=> Errors fixed to show login

operate/services/manage.py, operate/services/protocol.py
Allow update metadata fields. Namely, it allows update the description of the metadata file when minting a service to match the description passed in the service template.
This PR is a temporary solution for some refactor needed on Open Autonomy, and documented in a comment on the source code.
Important: this PR only allows updates in the description. However, placeholder values have been put for `name` and `attributes` to be properly implemented in OpenAutonomy.
=> Allow update metadata fields (description)

frontend/config/stakingPrograms/base.ts, frontend/context/RewardProvider.tsx, frontend/context/ServicesProvider.tsx, frontend/service/agents/Memeooor.ts
=> feat: add isEligibleForRewards logic, some fixes around loading states

frontend/config/activityCheckers.ts, frontend/config/stakingPrograms/base.ts, frontend/config/stakingPrograms/index.ts, frontend/constants/serviceTemplates.ts, frontend/enums/StakingProgram.ts, operate/ledger/profiles.py, templates/memeooorr.yaml
Update meme staking contract and its activity checker addresses
=> feat: update staking contract addresses

electron/store.js, frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/LowFunds.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/LowOperatingBalanceAlert.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/MainNeedsFunds.tsx, frontend/components/MainPage/sections/GasBalanceSection.tsx, frontend/config/stakingPrograms/base.ts, frontend/hooks/useNeedsFunds.ts, frontend/types/ElectronApi.ts
separate isInitialFunded into two variables by agent type
didn't support backward compatibility since we agreed to advice users not to switch back to old versions (due to BE will break) - but should think how to do it next time
this didn't work for me, too many issues (see "important" note): https://www.npmjs.com/package/electron-store#migrations
=> fix: make isInitialFunded by agent type

frontend/components/MainPage/sections/AlertSections/LowFunds/EmptyFunds.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/FundsToActivate.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/MainNeedsFunds.tsx, frontend/components/MainPage/sections/AlertSections/index.tsx, frontend/components/SettingsPage/DebugInfoSection.tsx, frontend/context/RewardProvider.tsx
reenable needs funds alert
fix duplicated master safes on debug page
=> fix: show needs funds alert, fix debug info

electron/main.js, frontend/components/SetupPage/SetupYourAgent/SetupYourAgent.tsx, frontend/components/SetupPage/SetupYourAgent/validation.ts, frontend/constants/serviceTemplates.ts, frontend/context/ElectronApiProvider.tsx, frontend/types/Cookies.ts, operate/services/manage.py, operate/services/utils/memeooorr.py
save twitter cookies stringified json to env variables so it can be then processed by BE
=> feat: saves twitter cookies to envs

frontend/config/stakingPrograms/index.ts, frontend/config/stakingPrograms/mode.ts, frontend/constants/serviceTemplates.ts, frontend/constants/urls.ts, frontend/enums/StakingProgram.ts, frontend/next.config.mjs
Add service template for Modius
Based on:
https://github.com/valory-xyz/modius-quickstart/blob/main/run_service.py#L434
https://github.com/valory-xyz/modius-quickstart/blob/main/run_service.py#L899
=> feat: add service template

electron/store.js, frontend/components/MainPage/sections/AlertSections/LowFunds/EmptyFunds.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/FundsToActivate.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/LowFunds.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/MainNeedsFunds.tsx, frontend/components/MainPage/sections/AlertSections/NewStakingProgramAlert.tsx, frontend/components/MainPage/sections/AlertSections/index.tsx, frontend/components/SetupPage/Create/SetupEoaFunding.tsx, frontend/config/agents.ts, frontend/config/tokens.ts, frontend/constants/serviceTemplates.ts, frontend/context/BalanceProvider.tsx, frontend/enums/Agent.ts, frontend/hooks/useNeedsFunds.ts, frontend/types/Agent.ts, frontend/types/ElectronApi.ts
add additional token requirements logic
=> feat: support additional tokens required for initial funding

frontend/components/MainPage/sections/AlertSections/LowFunds/FundsToActivate.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/MainNeedsFunds.tsx, frontend/components/MainPage/sections/OlasBalanceSection.tsx, frontend/components/YourWalletPage/YourAgent.tsx, frontend/components/YourWalletPage/index.tsx, frontend/hooks/useFeatureFlag.ts, frontend/hooks/useNeedsFunds.ts
1) some fixes around initial funding
2) enable feature flag and extend manage wallet page with erc20 tokens
=> feat: extend manage wallet with erc20 tokens

frontend/client/types.ts, frontend/constants/serviceTemplates.ts, operate/constants.py, operate/operate_types.py, operate/services/manage.py, operate/services/service.py, operate/utils/gnosis.py, operate/wallet/master.py, tox.ini
=> Feat: Support ERC20 in funding job

frontend/client/types.ts, frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx, frontend/components/MainPage/sections/AlertSections/LowFunds/FundsToActivate.tsx, frontend/config/agents.ts, frontend/config/stakingPrograms/mode.ts, frontend/constants/serviceTemplates.ts, frontend/hooks/useNeedsFunds.ts, frontend/service/agents/Modius.ts
=> feat: support funds by chain

frontend/client/types.ts, frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
for a short period of time we had a bug when the service hash has changed we updated the service with a service template leading to that the description was updated to the default one. there are services now that have default description, we should update them with the right one
old code:
=> fix: update service with correct description

operate/constants.py, operate/services/manage.py
=> Fix: Funding job to send amount upto the topup

frontend/context/ServicesProvider.tsx
I've had only modius service created, and when I switched to trader and tried to start it, it didn't create the service because the `selectedServiceConfigId` had old modius value
=> fix: service not created when switching between agents

frontend/components/MainPage/sections/RewardsSection/NotifyRewardsModal.tsx
sum total olas in wallets and staked when displaying reward modal
(missing staked olas here)
=> Fix Olas total balance in rewards modal

frontend/components/SetupPage/Create/SetupCreateSafe.tsx, frontend/constants/serviceTemplates.ts, frontend/hooks/useMultisig.ts, package.json, pyproject.toml
1) allow users to create a safe without backup wallet (we'll implement changing the backup wallet later using `PUT /api/wallet/safe` instead of referring to safe app)
2) update modius hash
=> fix: allow creating safe when there is no backup wallet

operate/services/protocol.py
PR: Fix staking duration calculation to use blockchain timestamp
Updates the staking duration calculation to use the blockchain's timestamp instead of local system time. This fixes potential time synchronization issues and ensures consistent validation across all nodes.
Before:
- Used local system time (`time.time()`)
- Could lead to inconsistent validation results
After:
- Uses on-chain block timestamp
- Guarantees consistent behavior across the network
=> updated staked_duration calc from python timestamp to ledger timestamp

electron/logger.js
Reduce logging amount for backend from 1000 files (10Gb) to 5 files (50Mb).
Note that with the current configuration of `winston.transports.File` the file rotation will only keep the latest `maxFiles` named `cli<N>.log ... cli<N+maxFiles-1>.log` for some N. The counter is always increasing. When space runs out, it will increase N and delete the oldest file.
If we include the option `tailable: true` it will always keep `cli.log ... cli<maxFiles-1>.log`, but in reverse order. The issue is that this will not delete already existing logs `>= maxFiles` for users that already have been running Pearl. 
=> Reduce logging amount

frontend/components/SetupPage/Create/SetupBackupSigner/BackupWalletManual.tsx, frontend/components/SetupPage/Create/SetupBackupSigner/BackupWalletWeb3Auth.tsx, frontend/components/SetupPage/Create/SetupCreateHeader.tsx, frontend/components/SetupPage/SetupWelcome.tsx
Redirect the user to the backup wallet screen (instead of agent onboarding, currently) if they kill the app without setting the backup signer address.
https://linear.app/valory-xyz/issue/OPE-197
=> fix: incomplete account setup - backup wallet not set
