valory-xyz/olas-operate-app

- .github/workflows/release.yml
Remove breaking main check from release.yml
> Remove breaking main check from release.yml

- frontend/components/Layout/Layout.tsx
- frontend/context/BalanceProvider.tsx
- frontend/context/MasterSafeProvider.tsx
- frontend/context/OnlineStatusProvider.tsx
- frontend/context/RewardProvider.tsx
- frontend/context/ServicesProvider.tsx
- frontend/context/WalletProvider.tsx
- frontend/pages/_app.tsx
in the video I first show that there are calls by interval, then turn off my Wi-Fi, show that there are no calls, and finally turn on Wi-Fi again - and there are calls again by interval.
https://github.com/valory-xyz/olas-operate-app/assets/22725775/cf62e10e-eac6-4e66-a137-6fad3c27b677
> Handle no internet connection

- electron/preload.js
- electron/store.js
- frontend/components/Setup/SetupWelcome.tsx
- frontend/context/ElectronApiProvider.tsx
> Clear store state when new account is created

- package.json
- yarn.lock
`adm-zip` dependency was missing, the require statement was importing a type from `typescript` dependency
> add adm-zip dependency

- electron/install.js
- package.json
- pyproject.toml
bump versions
(can ignore install.js lint)
> release: update version to 0.1.0rc47

- electron/install.js
- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
- templates/trader.yaml
> Release v0.1.0rc56

- frontend/constants/serviceTemplates.ts
- templates/trader.yaml
Update agent hash to trader_omen_gnosis service supporting own Thegraph endpoints.
> Update agent hash to support new Thegraph endpoints

- operate/services/manage.py
- operate/services/service.py
* Improve update service logic - deletion of old service folders
* Added some safeguard logic in the process
* Added further logging on update service logic
> Improve update service logic

- frontend/components/Main/MainGasBalance.tsx
Text change for: https://github.com/valory-xyz/olas-operate-app/issues/209
> Misleading tooltip text for Trading Balance

- operate/services/manage.py
Add further logs to isolate issue #210.
This logging is likely to be removed once #210 is resolved to prevent from excessive loging being recorded.
> Add further logs

- electron/install.js
- package.json
- pyproject.toml
> release: v0.1.0-rc64

- frontend/constants/serviceTemplates.ts
- templates/trader.yaml
Update trader hash to a dedicated Pearl market creator
> Update trader hash to a dedicated Pearl market creator

- electron/install.js
- operate/cli.py
- operate/services/health_checker.py
- operate/services/manage.py
- package.json
- pyproject.toml
the logic improved:
* healtchecker waits for tcp port up
* if not up in timeout - > restart
* if up -> check health response in cycle
* if not healthy 5 times in row -> restart
* no tcp port is up -> restart
* healthy - > reset fails counter to 0
> reimplemented healthcheck

- electron/install.js
- package.json
- pyproject.toml
> chore: bump to rc93

- frontend/components/Main/MainGasBalance.tsx
- frontend/components/Main/MainNeedsFunds.tsx
- frontend/components/Main/MainOlasBalance.tsx
- frontend/styles/globals.scss
1) Changed font color for primary alert so that it matches the Figma
2) Updated alert content as per design
> chore: update agent needs funds alert

- operate/services/manage.py
- operate/services/protocol.py
This PR adds support for updating the service from a safe.
> feat: add support for updates from safe

- operate/ledger/profiles.py
- operate/services/manage.py
- operate/services/protocol.py
This PR updates the staking flow.
> feat: add the staking flow

- frontend/components/ManageStakingPage/StakingContractSection/alerts.tsx
- frontend/components/ManageStakingPage/StakingContractSection/index.tsx
Confusion arose from previous deposit requirements.
Updated to calculate the requirement from master safe balance and staked balance.
Added calculated deposit requirement to determine whether to show the "not enough OLAS" alert prior to migrating to beta contract.
> Fix: Olas requirement calculation for migration (only master safe & staked balance)

- frontend/components/MainPage/sections/AddFundsSection.tsx
- frontend/components/ManageStakingPage/StakingContractSection/index.tsx
Added funding section from the main page to the Pearl Beta section.
This way it's clearer for users where/what they should fund.
> Add funding section to Staking Management page

- .gitleaksignore
- operate/cli.py
- operate/services/manage.py
- operate/services/protocol.py
- operate/services/service.py
- tox.ini
> Multichain support and (partial) review of on-chain flow

- operate/services/manage.py
Rename instead of delete invalid services
> Rename instead of delete invalid services

- operate/services/manage.py
Add timestamp to renamed invalid services
> Add timestamp to renamed invalid services

- README.md
- docs/dev/macos-setup.md
- docs/dev/rpcs.md
- docs/dev/ubuntu-setup.md
- docs/dev/windows-setup.md
README is messy, and there's limited / no public reference for Pearl contribution, developer setup
added `docs/` directory for public reference material
rewrote setup guides for each platform, linked from README
> docs: added platform specific docs for dev setup & windows guide

- .github/workflows/release_win.yml
- frontend/context/BalanceProvider.tsx
- missing `?`
- added win32 dev build
in response to QA on [Slack](https://valory-workspace.slack.com/archives/C07CKA5TN5V/p1727094943383149?thread_ts=1726835820.148059&cid=C07CKA5TN5V)
> fix: chain_configs undefined error, added win32 dev build

- frontend/components/SetupPage/Create/SetupCreateSafe.tsx
- frontend/components/styled/CardSection.tsx
staging UX for this error screen was butchered, fixed to remove X scrollbar and badly formatted bottom line.
> fix: safe creation error screen

- package.json
- pyproject.toml
> bump: rc168

- frontend/components/YourWalletPage/YourAgent.tsx
- package.json
- pyproject.toml
> hotfix: remove agent profile link

- .github/workflows/release.yml
- .github/workflows/release_win.yml
- update tenderly gnosis virtual testnet RPCs
> fix: update tenderly rpcs for dev releases

- frontend/components/YourWalletPage/YourAgent.tsx
- package.json
- pyproject.toml
- re-add agent profile link to Predict UI
---
Released as rc182
Merging to main, then will merge from main to staging
> feat: reinstate agent profile link to Predict

- frontend/components/ManageStakingPage/StakingContractSection/useMigrate.tsx
- frontend/constants/contractAddresses.ts
- frontend/constants/stakingProgramMeta.ts
- frontend/context/StakingContractInfoProvider.tsx
- frontend/context/StakingProgramProvider.tsx
- frontend/enums/StakingProgram.ts
- frontend/hooks/useStakingContractInfo.ts
- frontend/service/Autonolas.ts
- frontend/utils/service.ts
- operate/ledger/profiles.py
- package.json
- pyproject.toml
Add Pearl Beta 3, 4, 5 staking contracts
> Add Pearl Beta 3, 4, 5 staking contracts

- operate/services/health_checker.py
- operate/services/manage.py
- operate/services/service.py
Use environment variables to consistently configure the ledger overrides during building and running the agents
> Refactor (Configs): Ledger overrides

- frontend/components/MainPage/header/AgentButton.tsx
- frontend/components/MainPage/header/CannotStartAgentPopover.tsx
- frontend/components/MainPage/index.tsx
- frontend/components/MainPage/sections/AlertSections/AddBackupWalletAlert.tsx
- frontend/components/MainPage/sections/AlertSections/NoAvailableSlotsOnTheContract.tsx
- frontend/components/MainPage/sections/AlertSections/index.tsx
- frontend/components/MainPage/sections/StakingContractUpdate.tsx
- frontend/components/ManageStakingPage/StakingContractSection/CantMigrateAlert.tsx
- frontend/components/ManageStakingPage/StakingContractSection/CountdownUntilMigration.tsx
- frontend/components/ManageStakingPage/StakingContractSection/MigrateButton.tsx
- frontend/components/ManageStakingPage/StakingContractSection/StakingContractDetails.tsx
- frontend/components/ManageStakingPage/StakingContractSection/StakingContractTag.tsx
- frontend/components/ManageStakingPage/StakingContractSection/index.tsx
- frontend/components/ManageStakingPage/StakingContractSection/useMigrate.tsx
- frontend/context/StakingContractInfoProvider.tsx
- frontend/context/StakingProgramProvider.tsx
- frontend/enums/StakingProgramStatus.ts
- frontend/hooks/useNeedsFunds.ts
- frontend/hooks/useServices.ts
- frontend/hooks/useStakingContractInfo.ts
- frontend/hooks/useStakingProgram.ts
- frontend/utils/service.ts
- package.json
- pyproject.toml
fix migrations
fix initial deployment validation
fix funding requirements
fix no slots conditions
display available slots instead of max slots
created hook for managing single staking contracts instead of only the active contract
added "Default" staking program tag
added XDAI requirements for migration
disabled staking program switching will agent in transitional state to avoid breaking
only block agent deployment due to lacking slots if the service not staked
added several "is loaded" variables to conditions to ensure data is loaded before ingestion
added state for default staking program for better UX after selecting to switch contracts
> hotfix: fix migrations, initial deployment validation, funding requirements, no slots conditions

- operate/services/manage.py
- operate/services/service.py
Prevent corrupting service configurations due to unintended downgrades.
If a user upgrades the app, and then downgrades it, this will prevent the application from start (stuck on loading screen), but the logs will reflect the raised exception. Possibly a better error-handling framework should be designed (outside the scope of this PR).
This is possibly not a nice UX, but at least it prevents from corrupting the files. Also, it is expected that these kind of situations occur rarely (user installing version n-1 -> n -> n-1), and this can be unblocked by installing version 'n'. 
> Prevent unintended downgrade

- operate/data/contracts/uniswap_v2_erc20/contract.py
- operate/data/contracts/uniswap_v2_erc20/contract.yaml
- operate/data/contracts/uniswap_v2_erc20/tests/__init__.py
- operate/data/contracts/uniswap_v2_erc20/tests/test_contract.py
Use the same `uniswap_v2_erc20` as present in `liquidity-rebalancing`
> Chore: Update `uniswap_v2_erc20` as in liquidity-rebalancing

- frontend/client/types.ts
- frontend/constants/serviceTemplates.ts
- operate/operate_types.py
- operate/services/service.py
Add a single field in the JSON for alll the environment variables for the agents
> Add unified way for environment variables

- electron/main.js
- electron/processes.js
- package.json
- pyproject.toml
- kill application UI components first
- recent changes stopped quit from completing until `stop_all_services` endpoint resolved
- handle process killing in the background before electron exits
- added electron logging to `beforeQuit` and `killProcesses`
> Fix electron-related process killing

- api.md
- operate/cli.py
> Update API doc

- operate/services/utils/tendermint.py
> chore: flake8 lint fix for staging to main checks

- frontend/client/enums.ts
- frontend/client/types.ts
- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- frontend/components/MainPage/header/AgentButton/AgentRunningButton.tsx
- frontend/components/ManageStakingPage/StakingContractSection/MigrateButton.tsx
- frontend/components/ManageStakingPage/StakingContractSection/useMigrate.tsx
- frontend/constants/react-query-keys.ts
- frontend/context/BalanceProvider.tsx
- frontend/context/ServicesProvider.tsx
- frontend/context/WalletProvider.tsx
- frontend/enums/Wallet.ts
- frontend/hooks/useLogs.ts
- frontend/hooks/useService.ts
- frontend/hooks/useServices.ts
- frontend/service/Wallet.ts
- frontend/utils/middlewareHelpers.ts
- Refactor wallet provider x hooks
- Required to complete balance provider refactor
- Moved memoized services logic out of hook back to context, as it will re-run on every execution
> Refactoring wallets provider & hooks (was required for Balance provider refactor)

- operate/services/deployment_runner.py
Issue with unintended exception trace
> Issue with unintended exception trace

- frontend/constants/serviceTemplates.ts
- operate/services/service.py
- templates/trader.yaml
Override ledger address from an environment variable, which can be configured in the service template
> Refactor: Override ledger address from an env var

- frontend/components/MainPage/index.tsx
- frontend/components/MainPage/sections/OlasBalanceSection.tsx
- frontend/hooks/useBalanceContext.ts
Get OLAS balances from all wallets, including master, service, and staked olas
Display OLAS
Extended/fixed some balance hooks, as they were missing elements, and i.e. master safe exported staked balances (of which it should have none)
Better comments for balance hooks
> Main window Balance (aggregated OLAS balances)

- frontend/client/types.ts
- frontend/components/MainPage/header/AgentButton/AgentButton.tsx
- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- frontend/config/stakingPrograms/gnosis.ts
- frontend/config/stakingPrograms/index.ts
- frontend/constants/serviceTemplates.ts
- frontend/hooks/useStakingContractDetails.ts
- frontend/types/Autonolas.ts
- Update agent buttons with updated hooks
- Added mechType to STAKING_PROGRAMS for easier access
- Returned missing values from `useActiveStakingContractInfo`
> Refactor Agent buttons

- frontend/components/SettingsPage/index.tsx
- frontend/hooks/useMultisig.ts
Update backup wallet settings
Handle undefined fallbacks for useMultisig
> Backup wallet settings

- frontend/components/MainPage/header/index.tsx
- frontend/components/MainPage/index.tsx
- frontend/components/MainPage/modals/FirstRunModal.tsx
- frontend/components/MainPage/sections/AlertSections/LowTradingBalanceAlert.tsx
- frontend/components/MainPage/sections/GasBalanceSection.tsx
- frontend/components/MainPage/sections/KeepAgentRunningSection.tsx
update alerts and modals on main
> refactor: main alerts and modals

- frontend/client/enums.ts
- frontend/hooks/useNotifyOnNewEpoch.ts
- frontend/hooks/useService.ts
Fix lint errors on useNotifyOnNewEpoch
Added some deployment status related booleans for ease of use
> useNotifyOnNewEpoch, some small QoL additions to useService (isRunning, .etc)

- frontend/components/Pages/AddBackupWalletViaSafePage/index.tsx
- frontend/components/YourWalletPage/Titles.tsx
- frontend/components/YourWalletPage/YourAgent.tsx
- frontend/components/YourWalletPage/index.tsx
Fix lint errors, removed safe prop
> Fix lint errors around adding backup wallets to safe

- .github/workflows/release.yml
- build-win-tenderly.js
- build-win.js
- build.js
- build.tester.js
- download_binaries.sh
- electron/components/PearlTray.js
- electron/install.js
- electron/main.js
- package.json
Bulk renames
Commented optimus binary download for now
> Remove optimus downloads, renaming, workflows, .etc

- frontend/components/YourWalletPage/YourAgent.tsx
Fix lint errors in YourAgent component
Hacky implementation until we require n agents
> Fix YourAgent lint errors

- frontend/components/SettingsPage/DebugInfoSection.tsx
should display info regardless chosen homeChainId or service. unsure how it'll look, will need to debug, just to unblock app running
> refactor: debug section

- operate/cli.py
- operate/services/manage.py
- operate/services/protocol.py
- operate/utils/gnosis.py
- DRYed the mechanism to wait for transaction settlement
- Not skipping owner update when terminating the service while withdrawing
> Fix (Withdrawal): Transaction waiting to settle

- frontend/components/MainPage/sections/AlertSections/AddBackupWalletAlert.tsx
- frontend/components/Pages/AddBackupWalletViaSafePage/index.tsx
- frontend/hooks/useMultisig.ts
- frontend/service/Wallet.ts
Fixes to backup wallet setup and UX
> Fix backup wallet API, main window alert, onboarding setup

- frontend/components/MainPage/sections/NeedsFundsSection.tsx
- frontend/components/ManageStakingPage/StakingContractSection/CantMigrateAlert.tsx
- frontend/components/ManageStakingPage/StakingContractSection/MigrateButton.tsx
- frontend/components/ManageStakingPage/StakingContractSection/index.tsx
- frontend/components/ManageStakingPage/StakingContractSection/useMigrate.tsx
- frontend/constants/serviceTemplates.ts
- frontend/context/BalanceProvider.tsx
- frontend/context/RewardProvider.tsx
- frontend/context/StakingProgramProvider.tsx
- frontend/hooks/useNeedsFunds.ts
- frontend/hooks/useStakingProgram.ts
Some screens/videos of working UI
https://github.com/user-attachments/assets/94a34ae0-4074-43fd-a621-b401f325381b
> refactor: needs funds and migrate sections

- frontend/components/SettingsPage/DebugInfoSection.tsx
quickly discussed with Roman the multi-chain view
> refactor: logs update

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- frontend/components/MainPage/sections/RewardsSection/RewardsStreak.tsx
- frontend/components/MainPage/sections/RewardsSection/index.tsx
- frontend/components/ManageStakingPage/StakingContractSection/CantMigrateAlert.tsx
- frontend/components/SetupPage/Create/SetupCreateSafe.tsx
- frontend/context/MasterWalletProvider.tsx
- frontend/context/ServicesProvider.tsx
- frontend/context/StakingProgramProvider.tsx
- frontend/hooks/useLogs.ts
- frontend/hooks/useNeedsFunds.ts
- frontend/hooks/useRewardsHistory.ts
1) fix safe creation retries
2) fix "Cannot start agent" shown after onboarding
3) removed rewards bottom border
> fix: safe creation multiple times, incorrect button state after onboarding

- operate/cli.py
Checksum the address when it's coming as input
> Fix: Checksum input address

- operate/services/manage.py
Ignore it for now to not negatively affect the DAAs
> Fix: Ignore insufficient funds while starting agent

- electron/main.js
- package.json
- pyproject.toml
> app autostart

- frontend/abis/memeActivityChecker.ts
- frontend/config/activityCheckers.ts
- frontend/config/agents.ts
- frontend/config/olasContracts.ts
- frontend/config/stakingPrograms/base.ts
- frontend/config/stakingPrograms/index.ts
- frontend/config/tokens.ts
- frontend/enums/Agent.ts
- frontend/enums/StakingProgram.ts
- frontend/service/agents/Memeooor.ts
> chore: extend configs with memeooor

- .github/workflows/release.yml
- electron/install.js
- operate/services/deployment_runner.py
> tm mac bundle in

- frontend/client/types.ts
- frontend/constants/serviceTemplates.ts
> feat: update service config template

- .github/workflows/release.yml
- Makefile
- operate/services/deployment_runner.py
- package.json
- pyproject.toml
> extract aea_bin and tendermint exec from the pearl exec

- frontend/components/MainPage/sections/OlasBalanceSection.tsx
- frontend/components/MainPage/sections/RewardsSection/StakingRewardsThisEpoch.tsx
- frontend/components/SettingsPage/DebugInfoSection.tsx
- frontend/components/SetupPage/SetupYourAgent/validation.ts
- frontend/constants/urls.ts
- frontend/context/BalanceProvider.tsx
- frontend/graphql/queries.ts
- frontend/hooks/useRewardsHistory.ts
- frontend/service/agents/StakedAgentService.ts
> chore: fix dummy service requests

- api.md
- operate/cli.py
- operate/ledger/profiles.py
- operate/services/manage.py
- operate/services/service.py
Backend changes to support memeooorr
> Feat (Memeooorr): Support in the backend

- operate/services/deployment_runner.py
> path fix for bundled in tendermint excutable search

- api.md
- (Protocol) #400 (Continuation from branch)
- (Refactor/Config) Support multiple services on middleware (this PR)
- (Refactor) #422
- (Refactor/Config) #430
- (Refactor/Cleanup) #437
- (Refactor/Cleanup) #441
- (Refactor/Config) #442
- (Refactor/Config) #444 
- (Doc) #446
- (Doc) #450
- (Refactor) #451
- (Refactor/Config) #452
- (Refactor/Config) #458
- (Tests) #459
- (Refactor) #460 
- (Feature) #464 
- `operate/operate_types.py`
- `operate/ledger/*`
- `operate/services/manage.py`
- `operate/services/protocol.py`
- `operate/utils/gnosis.py`
- `operate/wallet/master.py`
> Allow multiple services on middleware (Major refactor)

- operate/services/deployment_runner.py
- package.json
- pyproject.toml
> fix tm mac exec path on staging fter merging with main

- frontend/constants/serviceTemplates.ts
- operate/ledger/__init__.py
- operate/ledger/profiles.py
- operate/services/manage.py
- operate/services/utils/memeooorr.py
- templates/memeooorr.yaml
Misc fixes for Memeooorr agent
> Misc backend fixes for Memeooorr agent

- frontend/components/ManageStakingPage/StakingContractSection/MigrateButton.tsx
- frontend/service/Services.ts
> fix: hardcoded chain Id in service creation

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- Fix from staging/refactor merge; updates service deployed agent hash is incorrect (due to update)
> Fix service conditional update step

- frontend/constants/serviceTemplates.ts
Fix service template funding requirements for Memeooorr
> Fix service template funding requirements for Memeooorr

- electron/main.js
> fix: hide user input values in debug_data (export logs)

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- frontend/components/SetupPage/Create/SetupCreateSafe.tsx
- frontend/hooks/useMultisig.ts
- Fallback to backup safe during on-boarding, if backup signer is not set (via first load)
- Require backup address consistency if deploying agent, and safe does not exist yet
> Backup wallet address fixes

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- package.json
- pyproject.toml
Fix logic for starting agents
Released to early adopters as rc39 
> Fix start button logic (v0.2.0-rc39)

- frontend/constants/serviceTemplates.ts
- templates/memeooorr.yaml
> Update Memeooorr hash

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
> Fix "update service" returning, should await

- operate/keys.py
- operate/services/deployment_runner.py
- operate/services/manage.py
- operate/services/protocol.py
- operate/services/service.py
- operate/wallet/master.py
Update on-chain service if description changes
> Update on-chain service if description changes

- frontend/constants/serviceTemplates.ts
- templates/memeooorr.yaml
> Update agent hash

- frontend/constants/serviceTemplates.ts
- operate/services/manage.py
> Fix: modius configs

- frontend/config/stakingPrograms/mode.ts
- operate/ledger/profiles.py
Checksum staking contract address
> Checksum staking contract address

- operate/ledger/profiles.py
- operate/services/manage.py
> Fix: Contract addresses and env-var for optimus

- frontend/context/RewardProvider.tsx
- frontend/service/agents/Modius.ts
Fix modius rewards earned tag not being shown
> fix: modius rewards not being shown

- operate/services/service.py
Fixes a bug in service template migration if it's migrating directly from version <4 to 5
> Fix: Allow service template migration from <4 to 5

- frontend/components/MainPage/sections/OlasBalanceSection.tsx
> fix: include rewards in balance

- frontend/constants/serviceTemplates.ts
> chore: update modius hash

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
If fixed variables are changed in the template - update the service 
> chore: update fixed env variables if changed in the template

- frontend/constants/serviceTemplates.ts
- frontend/hooks/useFeatureFlag.ts
> feat: enable agent activity for modius

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- frontend/utils/service.ts
Update the service if funds requirements were changed
> chore: update fund requirements, refactor service update code

- frontend/constants/serviceTemplates.ts
> fix: agents.fun hash update

- frontend/context/BalanceProvider.tsx
for some reason typescript locally handles the filtering fine, but the build fails
added alias as a quick solution
> fix failing build

- frontend/components/SettingsPage/index.tsx
- frontend/components/SetupPage/Create/SetupCreateSafe.tsx
1) Fix allBackupAddresses getter (was empty without passing masterSafes to the hook)
2) Use home chain master safe to display backup wallet correctly
> fix: adding backup wallet to master safe

- frontend/utils/service.ts
Add the logic to update the service when there's a new Fixed or Computed env variable in the template which doesn't exist in the service
> fix: ensure new variables are updated in the service

- frontend/components/MainPage/sections/SwitchAgentSection.tsx
- frontend/constants/colors.ts
> feat: show disabled settings for predict

- frontend/config/agents.ts
- frontend/constants/serviceTemplates.ts
- operate/services/health_checker.py
- package.json
- pyproject.toml
- templates/optimus.yaml
> Adjust healthcheck - Modius

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- frontend/components/UpdateAgentPage/context/UpdateAgentProvider.tsx
- frontend/constants/serviceTemplates.ts
- frontend/utils/service.ts
Fix PATCH not called for memeooor
We need to either remember that we compare services with templates by name and keep the name the same, or have a unique id in each service
> fix: service update for memeooorr

- .github/workflows/release_win.yml
- Makefile
- frontend/config/agents.ts
- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
- templates/optimus.yaml
- templates/trader.yaml
Fix Pyinstaller AEA version. Addresses Trader kwargs issue, Modius issues.
> Fix Pyinstaller AEA version

- frontend/components/SetupPage/Create/SetupCreateSafe.tsx
- frontend/components/SetupPage/SetupYourAgent/validations.ts
- frontend/hooks/useNeedsFunds.ts
- package.json
- pyproject.toml
wait until we have backup wallet loaded in order to create safe with it
Pls, check the note and lmk your thoughts, that was the quickest solution
> Fix backup wallet not loaded on time

- operate/services/manage.py
Only check native tokens to set allow_start_agent = false, when either
MasterSafe + AgentSafe = 0
or 
MasterSafe + AgentEOA = 0
> Only check native tokens

- .github/workflows/release.yml
- .github/workflows/release_win.yml
> chore: update test nets

- operate/cli.py
- operate/services/health_checker.py
- operate/services/service.py
- package.json
- pyproject.toml
Fix healthcheck start, store previous logs
> Fix healthcheck start, store previous logs

- electron/main.js
Added prev_log.txt agent logs to export
> Added prev_log.txt agent logs to export

- frontend/config/agents.ts
- frontend/hooks/useFeatureFlag.ts
- package.json
- pyproject.toml
> release: trader activity tracker

- frontend/constants/serviceTemplates.ts
- operate/services/deployment_runner.py
- operate/services/manage.py
- package.json
- pyproject.toml
- templates/optimus.yaml
> Fix modius store path

- frontend/config/agents.ts
- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
- templates/trader.yaml
> Update pearl trader to 0.23.1

- frontend/service/Wallet.ts
Send 0 fund amount to middleware on safe creation
> 0 funding for safe creation requests

- README.md
- frontend/constants/serviceTemplates.ts
- operate/services/health_checker.py
- package.json
- pyproject.toml
- templates/memeooorr.yaml
- templates/trader.yaml
* Update trader with service kwargs
* Update memeooorr with fixed UTF-8 issue on Windows
> Update trader, memeooorr

- operate/cli.py
- operate/services/health_checker.py
- operate/services/manage.py
- operate/services/protocol.py
- operate/services/service.py
Return latest healthcheck or empty JSON if no latest healthcheck.
> Return latest healthcheck

- frontend/constants/serviceTemplates.ts
- templates/memeooorr.yaml
> chore: update memeooorr hash

- frontend/components/Layout/TopBar.tsx
> feat: update from "alpha" to "beta"

- poetry.lock
- pyproject.toml
> Bump middleware

- frontend/config/activityCheckers.ts
- frontend/config/stakingPrograms/base.ts
- frontend/config/stakingPrograms/celo.ts
- frontend/config/stakingPrograms/gnosis.ts
- frontend/config/stakingPrograms/mode.ts
Connect activity checkers with staking contracts
> fix: set up correct activity checkers for all contracts

- frontend/constants/serviceTemplates.ts
- templates/memeooorr.yaml
> feat: update memeooorr hash

- .github/workflows/release_dev.yml
- .github/workflows/release_win_dev.yml
- package.json
- pyproject.toml
Separate prod and dev release
tags should match `"v*.*.*"` for prod releases
and `"dev-v*.*.*"` for dev releases
1) should help a little with signatures problem for windows
2) should create needed assets faster (sometimes the dev- ones are done first)
3) should have reduced time needed for building windows, but it didn't 😢 
> Chore: split releases

- frontend/constants/urls.ts
Update subgraphs for memeooorr and modius
> chore: update subgraphs endpoints to public

- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
- templates/optimus.yaml
> feat: add env variable for modius

- frontend/constants/serviceTemplates.ts
- templates/memeooorr.yaml
> Fix missing memeooorr vars

- frontend/constants/serviceTemplates.ts
- poetry.lock
- pyproject.toml
- templates/optimus.yaml
Update Modius hash, bump framework
> Update Modius hash, bump framework

- frontend/constants/serviceTemplates.ts
- templates/trader.yaml
> feat: update trader hash

- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
- templates/optimus.yaml
- templates/trader.yaml
> release: 0.2.0-rc225

- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
> feat: add accuracy hasn env variable

- docs/withdraw_manually.md
> Minor fix in doc

- frontend/components/MainPage/header/AgentButton/AgentNotRunningButton.tsx
- frontend/hooks/useBalanceContext.ts
- package.json
- pyproject.toml
keep only logic related to agent staking status and staking contract itself;
instead of checking balances use `canStartAgent` from refill requirement endpoint
> feat: update start agent button logic

- frontend/config/agents.ts
- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
- templates/optimus.yaml
> release: 0.2.0-rc239

- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
- templates/optimus.yaml
> feat: update modius hash

- docs/change_password.md
> Change password instructions

- frontend/components/YourWalletPage/AgentTitle.tsx
- frontend/constants/serviceTemplates.ts
> Staging to staging-ea

- .github/workflows/release_win.yml
- .github/workflows/release_win_dev.yml
- package.json
- pyproject.toml
> signature windows  fix

- frontend/constants/serviceTemplates.ts
> feat: update tools accuracy hash

- frontend/components/bridge/DepositForBridging.tsx
- frontend/styles/globals.scss
Adds tooltips; should show the "fluctuate" hint for native tokens
> feat: add tooltips

- package.json
- pyproject.toml
> release: 0.2.0-rc258

- frontend/constants/serviceTemplates.ts
- frontend/context/RewardProvider.tsx
- frontend/service/agents/AgentsFunBase.ts
- frontend/service/agents/AgentsFunCelo.ts
- frontend/service/agents/Modius.ts
- frontend/service/agents/PredictTrader.ts
- frontend/service/agents/shared-services/AgentsFun.ts
- package.json
- pyproject.toml
- templates/optimus.yaml
1) update accuracy hash for trader
2) update modius hash with changes for portfolio
3) fix number overflow issue
> Release 0.2.0-rc166

- frontend/constants/serviceTemplates.ts
- package.json
- pyproject.toml
1) update trader accuracy hash
2) add mech interact timeout for trader
> feat: update accuracy hash and set mech interact timeout

- package.json
- poetry.lock
- pyproject.toml
> release: 0.2.0-rc170

- frontend/constants/urls.ts
with regards to https://github.com/valory-xyz/olas-website/pull/279
> Change download link for better analytics tracking

- frontend/components/MainPage/header/AgentProfileButton.tsx
- frontend/constants/serviceTemplates.ts
Enable the ability to display predict UI inside Pearl
> feat: show predict UI inside Pearl

- package.json
- pyproject.toml
Update version number and release signed version
Will merge to staging after this is merged to main
> hotfix: 0.2.0-rc187 signed release

- frontend/constants/serviceTemplates.ts
- package.json
- poetry.lock
- pyproject.toml
> Fix: Default priority mech from MM address

- frontend/components/MainPage/sections/AlertSections/UnderConstruction.tsx
When balance is 100:
When balance is 0:
> chore: remove withdraw button when olas balance is 0

- poetry.lock
- pyproject.toml
> Fix: Permissing error on windows in KeysManager

- frontend/components/OnRampIframe/OnRampIframe.tsx
- frontend/components/SetupPage/Create/SetupOnRamp/PayingReceivingTable/useTotalFiatFromNativeToken.ts
- frontend/constants/urls.ts
- frontend/hooks/useFeatureFlag.ts
- frontend/yarn.lock
> feat: integrate proxy gateways for on ramping

- electron/main.js
- package.json
- yarn.lock
> chore: add developer tools menu

- poetry.lock
- pyproject.toml
> Feat: Rewards transfer from Agent safe to Master safe

- frontend/components/MainPage/sections/SwitchAgentSection.tsx
- frontend/components/MainPageV1/Home/Overview/AgentInfo/AgentDisabledAlert/styles.tsx
- frontend/components/MainPageV1/Home/Overview/AgentInfo/index.tsx
- frontend/components/MainPageV1/Home/Overview/Staking.tsx
- frontend/components/RewardsHistory/RewardsHistory.tsx
- frontend/components/YourWalletPage/index.tsx
> fix: type errors

- frontend/components/SetupPage/SetupWelcome.tsx
- frontend/styles/globals.scss
- frontend/theme/index.ts
Button restyles.
https://github.com/user-attachments/assets/cb8f6722-c03f-4f22-b56e-f0cc3dcc606f
> Style: buttons

- electron/main.js
- electron/preload.js
- electron/windows/termsAndConditions.js
- frontend/components/Layout/TopBar.tsx
- frontend/components/SetupPage/Create/SetupBackupSigner/BackupWalletWeb3Auth.tsx
- frontend/components/SetupPage/Create/SetupOnRamp/OnRampPaymentSteps/useBuyCryptoStep.tsx
- frontend/components/SetupPage/Create/SetupPassword.tsx
- frontend/constants/urls.ts
- frontend/context/ElectronApiProvider.tsx
- frontend/pages/terms-and-conditions.tsx
1) add terms and conditions for web3auth integration using the same window for terms and conditions as for transak
2) move terms window to a separate file for main.js readability
> feat: add web3auth terms and conditions

- frontend/components/MainPageV1/Home/Overview/AgentInfo/AgentDisabledAlert/index.tsx
- frontend/components/MainPageV1/Home/Overview/AgentInfo/AgentRunButton/AgentRunningButton.tsx
- frontend/components/MainPageV1/Sidebar.tsx
- frontend/service/agents/PredictTrader.ts
1) fix several sidebar menu items selected at a time - now there's only one
2) fix incorrect pausing state shown - added delay to reset pause
3) fix no slots available alert shown between running and earned reward states (was due to incorrect check for boolean)
4) checked evicted and earned rewards state shown correctly
> fix: edge cases

- .husky/pre-commit
- frontend/yarn.lock
- package.json
- yarn.lock
> fix: lockfile conflicts

- frontend/components/AgentWallet/BalancesAndAssets/BalancesAndAssets.tsx
- frontend/components/MainPageV1/Home/Overview/AgentInfo/AgentDisabledAlert/index.tsx
- frontend/components/MainPageV1/Home/Overview/Performance.tsx
- frontend/components/MainPageV1/Home/Overview/Staking.tsx
- frontend/components/MainPageV1/Home/index.tsx
- frontend/components/MainPageV1/index.tsx
1. Fixes underconstruction agent alerts.
2. Scroll to the top when the agent type is changed.
3. Copy change for eviction alert on agent wallet page. Also, only show the disabled withdraw button (& alert) when the agent is not eligible for re-staking.
> fix: under construction agent + eviction alerts
